version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: stark_ai
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: dev123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups

volumes:
  postgres_data: